### ISSUE TITLE
The CARLA fine-tuned versions

### ISSUE THREAD

**Issue by liuzichennwpu** [retis-ai/SemSegAdvPatch#4]
Could you please provide the CARLA fine-tuned versions.

**Comment by federiconesti** [comment]
Hello, please write an email to the authors to request the weights.

**Comment by liuzichennwpu** [comment]
Hello, I want to request the weights. My use of it will be limited to academic research only and will not be used commercially. Thanks again!



At 2024-01-03 21:41:03, "federiconesti" ***@***.***> wrote:

Hello, please write an email to the authors to request the weights.

**Comment by federiconesti** [comment]
Yeah I meant write an email directly to the author's email address, which is included in the paper. Thanks.
